# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import side_camera_image_service_pb2 as side__camera__image__service__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in side_camera_image_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SideCameraImageServiceStub(object):
    """Experimental service for side camera image submission - intended for prototyping only
    TODO: This service is temporary and should not be used in production
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitSideCameraImage = channel.stream_unary(
                '/ai.caper.cv.cart.domain.SideCameraImageService/SubmitSideCameraImage',
                request_serializer=side__camera__image__service__pb2.SubmitCameraFrameRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ObservePredictions = channel.unary_stream(
                '/ai.caper.cv.cart.domain.SideCameraImageService/ObservePredictions',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=side__camera__image__service__pb2.ObservePredictionsResponse.FromString,
                _registered_method=True)


class SideCameraImageServiceServicer(object):
    """Experimental service for side camera image submission - intended for prototyping only
    TODO: This service is temporary and should not be used in production
    """

    def SubmitSideCameraImage(self, request_iterator, context):
        """Submit a single side camera image for processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObservePredictions(self, request, context):
        """Listen for prediction events to come in
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SideCameraImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitSideCameraImage': grpc.stream_unary_rpc_method_handler(
                    servicer.SubmitSideCameraImage,
                    request_deserializer=side__camera__image__service__pb2.SubmitCameraFrameRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ObservePredictions': grpc.unary_stream_rpc_method_handler(
                    servicer.ObservePredictions,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=side__camera__image__service__pb2.ObservePredictionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.caper.cv.cart.domain.SideCameraImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.caper.cv.cart.domain.SideCameraImageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SideCameraImageService(object):
    """Experimental service for side camera image submission - intended for prototyping only
    TODO: This service is temporary and should not be used in production
    """

    @staticmethod
    def SubmitSideCameraImage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ai.caper.cv.cart.domain.SideCameraImageService/SubmitSideCameraImage',
            side__camera__image__service__pb2.SubmitCameraFrameRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObservePredictions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.caper.cv.cart.domain.SideCameraImageService/ObservePredictions',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            side__camera__image__service__pb2.ObservePredictionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
