# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: side_camera_image_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'side_camera_image_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fside_camera_image_service.proto\x12\x17\x61i.caper.cv.cart.domain\x1a\x1bgoogle/protobuf/empty.proto\"z\n\x18SubmitCameraFrameRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x16\n\tcamera_id\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x16\n\ttimestamp\x18\x03 \x01(\x03H\x01\x88\x01\x01\x42\x0c\n\n_camera_idB\x0c\n\n_timestamp\"O\n\x1aObservePredictionsResponse\x12\x12\n\x08json_raw\x18\x01 \x01(\tH\x00\x12\x12\n\x08\x66ile_raw\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload2\xe3\x01\n\x16SideCameraImageService\x12\x64\n\x15SubmitSideCameraImage\x12\x31.ai.caper.cv.cart.domain.SubmitCameraFrameRequest\x1a\x16.google.protobuf.Empty(\x01\x12\x63\n\x12ObservePredictions\x12\x16.google.protobuf.Empty\x1a\x33.ai.caper.cv.cart.domain.ObservePredictionsResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'side_camera_image_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITCAMERAFRAMEREQUEST']._serialized_start=89
  _globals['_SUBMITCAMERAFRAMEREQUEST']._serialized_end=211
  _globals['_OBSERVEPREDICTIONSRESPONSE']._serialized_start=213
  _globals['_OBSERVEPREDICTIONSRESPONSE']._serialized_end=292
  _globals['_SIDECAMERAIMAGESERVICE']._serialized_start=295
  _globals['_SIDECAMERAIMAGESERVICE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
